import type { Video } from "@/types";
import { parseVideoTags } from "@/lib/parser/tagParser";

const seed = [
  { id: "2kqJSxQsc8I", title: "Morning walk to Zushi beach, river, Kanagawa" },
  { id: "n4c8k8IBR70", title: "Winter Zushi walk - hills and the sea, park, Kanagawa" },
  { id: "5DXZx9W17Ik", title: "Ishigami-mae station - rural Tokyo walk, river" },
  { id: "wxIFU9s5Irw", title: "Hachioji, Takao - rural Tokyo walk" },
  { id: "U2ILWYcbtrA", title: "Rural Tokyo, Ome at sunset" },
  { id: "PF-BNCDM9AE", title: "Tokyo snowfall 2026" },
  { id: "QNGD12JW5Lk", title: "Snowfall in Niigata, Japan" },
  { id: "6P5KQeawY2Q", title: "Tokyo Yomiuriland Lights" },
  { id: "oya1IzAwKw0", title: "Tokyo walk on New Year night" },
  { id: "ejNS-ri3siU", title: "Christmas Lights annual check at Enoshima, Japan" },
  { id: "xk_728NJ4vo", title: "Tokyo Odaiba Fireworks and Christmas Lights" },
  { id: "lIbzMQJAF6o", title: "Yokohama Minato-mirai Christmas Lights, Japan" },
  { id: "Dt4nDSb5FW0", title: "Back side of Tachikawa - sunset walk, Tokyo" },
  { id: "yKi3pFNK5TI", title: "Tokyo Marunouchi and Ginza Christmas Lights 2025-2026, Japan" },
  { id: "O1ckwNtnmlM", title: "Minato Christmas Lights walk - Tokyo tower, Azabu, Roppongi Hills, Midtown (Fixed)" },
  { id: "wea9bFNGtV4", title: "To Chichibu sunset, Saitama, Japan" },
  { id: "I6ZsokzXIo0", title: "Tokyo Mitake in red and gold - fall hike and fly by" },
  { id: "IZSxmLaWfK0", title: "The fall at night Omiya, Japan" },
  { id: "qUDMO_7c5_M", title: "Back to Akiruno - rural Tokyo walk" },
  { id: "jFxIaOLdgNM", title: "Night Tokyo walk - From Hino to Tama" },
  { id: "fQ1fcFKoV3g", title: "Saitama Chichibu walk on a gloomy day, Japan" },
  { id: "AH_N9UPuDxc", title: "Kawagoe festival, Japan" },
  { id: "1-FOaxPm41s", title: "Bakeneko festival, Tokyo" },
  { id: "s6V09zXuhAg", title: "Tokyo Odaiba candles event" },
  { id: "Qs0rxuYuJu4", title: "Gloomy to sunny walk in Oyama town, Shizuoka, Japan" },
  { id: "kEr_lGSdLjI", title: "Night Tsukishima walk, Tokyo" },
  { id: "Gg2B8xfwUvo", title: "Night walk at Otsuki, Yamanashi, Japan" },
  { id: "mitW9jkD3cU", title: "Nowhere in rural Ashigakubo road 299 walk, Saitama, Japan" },
  { id: "hmKS5TAVgWk", title: "Rural Tokyo - Akiruno town under dramatic sky, Japan" },
  { id: "QsZhnyJv4r0", title: "Night walk in Kanagawa towards Enoshima, Japan 2025 • 4K" },
  { id: "3VbdqaYIBxs", title: "Walking and flying at sunset in Iruma city, Saitama, Japan" },
  { id: "Is1Mk7M95I0", title: "After-walk - A bit walking and riding by bus in Iruma city, Saitama, Japan" },
  { id: "5n7KRVJrTrk", title: "Night rural Tokyo walk - Hamura-Fussa, Japan" },
  { id: "ipgknAYyAW0", title: "After-walk - dark Takashimadaira, Japan" },
  { id: "aVyuWb9F-SA", title: "Evening Tokyo Takashimadaira, Japan" },
  { id: "3sEyBMeT1lA", title: "Tokyo Okutama Noryo Festival with fireworks, Japan" },
  { id: "wYzlH92cyQY", title: "Edo river fireworks, Ichikawa side, Japan" },
  { id: "PzEHZ72nkPE", title: "Ichikawa day to sunset walk before fireworks, Japan" },
  { id: "ficUaqvN7E4", title: "Seashore town and beach walk - Kugenuma and Katase-nishinuma beaches, Japan" },
  { id: "0vgY_LWLxHA", title: "Tokyo Sumida river fireworks" },
];

export function getSeedVideos(): Video[] {
  return seed.map(({ id, title }) => ({
    id,
    title,
    description: "",
    thumbnail: `https://i.ytimg.com/vi/${id}/hqdefault.jpg`,
    publishedAt: "2023-01-01T00:00:00Z",
    channelId: "UCAcsAE1tpLuP3y7UhxUoWpQ",
    tags: parseVideoTags(title, ""),
  }));
}
